# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\x07\x65xample\"7\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04week\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"3\n\nSayGoodBye\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"\x1f\n\x0cGoodByeReply\x12\x0f\n\x07message\x18\x01 \x01(\t2C\n\x07Greeter\x12\x38\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x13.example.HelloReply\"\x00\x32\x44\n\nFareweller\x12\x36\n\x06SayBye\x12\x13.example.SayGoodBye\x1a\x15.example.GoodByeReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_HELLOREQUEST']._serialized_start=29
  _globals['_HELLOREQUEST']._serialized_end=84
  _globals['_HELLOREPLY']._serialized_start=86
  _globals['_HELLOREPLY']._serialized_end=115
  _globals['_SAYGOODBYE']._serialized_start=117
  _globals['_SAYGOODBYE']._serialized_end=168
  _globals['_GOODBYEREPLY']._serialized_start=170
  _globals['_GOODBYEREPLY']._serialized_end=201
  _globals['_GREETER']._serialized_start=203
  _globals['_GREETER']._serialized_end=270
  _globals['_FAREWELLER']._serialized_start=272
  _globals['_FAREWELLER']._serialized_end=340
# @@protoc_insertion_point(module_scope)
