image: node:lts-bullseye-slim

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

default:
  cache:  # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - server/.npm/
      - metro-map-client/.npm

lint:
  stage: test
  before_script:
    - cd server && npm ci --cache .npm --prefer-offline && cd ../metro-map-client && npm ci --cache .npm --prefer-offline
  script:
    - ./node_modules/eslint/bin/eslint.js --ext .js,.jsx,.mjs,.cjs 
  allow_failure: false

stages:
  - build
  - test
  - deploy

build-frontend:
  stage: build
  cache:
    key:
      prefix: 'frontend'
      files:
        - 'metro-map-client/package-lock.json'
    paths:
      - 'metro-map-client/node_modules/'
  script:
    - cd metro-map-client && npm install && npm run build
  only:
    refs:
      - main
      - master
      - staging
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - metro-map-client/build
      - metro-map-client/node_modules

build-backend:
  stage: build
  cache:
    key:
      prefix: 'backend'
      files:
        - 'server/package-lock.json'
    paths:
      - 'server/node_modules/'
  script:
    - cd server && npm install
  only:
    - main
    - master
    - staging
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - server/node_modules

